"""Transaction remove sumbol

Revision ID: 6ebbe7bdca63
Revises: 4759ca2ac290
Create Date: 2024-06-30 12:52:36.315368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebbe7bdca63'
down_revision = '4759ca2ac290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('currency_symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
